name: Staging deployment

on: 
  pull_request:
    types: [labeled]
    
env:
  DOCKER_IMAGE_NAME: yurieastwood-azure-ttt3
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  AZURE_WEBAPP_NAME: yurieastwood-ttt3-app

jobs:
  build:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')
